### ISSUE TITLE
yaml parser dependency

### ISSUE THREAD

**Issue by mluckcuck** [autonomy-and-verification-uol/ROSMonitoring#2]
Minor thing, but the dependency for the yaml parser isn't mentioned. I tried to run the generator and got:

```
matt@Vesta:~/Work/ROSMonitoring/generator$ ./generator --config_file offline_config.yaml 
Traceback (most recent call last):
  File "./generator", line 27, in <module>
    import yaml
ImportError: No module named yaml
```
Installed using `pip install pyyaml` and it seems fine. Just thought it should be mentioned.

**Comment by AngeloFerrando** [comment]
README updated (Thanks!)

**Comment by mluckcuck** [comment]
No worries. :)
