### ISSUE TITLE
GPU requirement for running the ROSMonitoring

### ISSUE THREAD

**Issue by everskyrube** [autonomy-and-verification-uol/ROSMonitoring#20]
Hi, could you advise if following GPU is capable enough for running the ROSMonitoring?

Nvidia RTX A1000 GPU w/ 4GB RAM

Thanks in advance for your time and response.

**Comment by AngeloFerrando** [comment]
Hi @everskyrube,

As far as I know, ROSMonitoring does not rely on GPU. Specifically, ROSMonitoring can be divided into the generation step and the monitoring step. In the generation step, a Python script synthesizes the monitor nodes necessary to gather all the information passed in the input YAML configuration file (such as topics, and services). In the monitoring step, these monitors can be run in ROS (either 1 or 2, depending on whether you are using the master branch or the ros2_devel one). Even in this case, they are all implemented in Python and executed as nodes of the system.

Therefore, I would say that a GPU could be useful if you are interested in running some Gazebo simulations or similar tasks. But for the pure purpose of ROSMonitoring, you should not need to worry too much about it (I guess).

I hope this was helpful. Of course, if you need additional information, let me know!

Cheers,
Angelo

**Comment by everskyrube** [comment]
@AngeloFerrando Thanks for your swift response.

**Comment by AngeloFerrando** [comment]
No worries, happy to help. If you try ROSMonitoring and you have any other doubts or issues let me know! 

Cheers,
Angelo
