### ISSUE TITLE
roslaunch cannot find monitor0.py

### ISSUE THREAD

**Issue by mluckcuck** [autonomy-and-verification-uol/ROSMonitoring#4]
I've copied the monitor folder from the ROSMonitoring folder into catkin_ws/src, then I ran `catkin_make`. 

Then I run `roslaunch src/monitor/run.launch`
and I get `ERROR: cannot launch node of type [monitor/monitor0.py]: can't locate node [monitor0.py] in package [monitor]`

the `run.launch` file has `<node pkg="monitor" type="monitor0.py" name="monitor0" output="screen"/>` so I can't see what the problem is.

**Comment by mluckcuck** [comment]
Turns out that I needed to run this `chmod +x src/monitor/src/monitor.py` (but with the name changed to `monitor0.py` but that was in the next step! 

This chmod just needs putting earlier in the instructions.

**Comment by AngeloFerrando** [comment]
Moved up in README. Thanks!
