### ISSUE TITLE
Monitor0.py cannot find monitor.msg

### ISSUE THREAD

**Issue by mluckcuck** [autonomy-and-verification-uol/ROSMonitoring#5]
I'm running `mattlck@mattlck:~/catkin_ws$ roslaunch src/monitor/run.launch`

and getting `ImportError: No module named monitorerror.msg` which then kills the process `[monitor0-2] process has died ...`

The folder monitor/msg has only `MonitorError.msg` inside, I don't know if this is relevant.

**Comment by AngeloFerrando** [comment]
You need to source ~/catkin_ws/devel/setup.bash after doing catkin_make.
Or you can just add it in your .bashrc
